### ISSUE TITLE
prep terraforms script not working

### ISSUE THREAD

**Issue by paulinuk** [chrisvugrinec/apim-demo#1]
Hello

When I run the script .\1_prep-terraform.sh

In your video you get information come up, but I dont

Also how do I get the enterprise app id and where do I set it?

Presuming that things have changed in Azure since this was done

```
$ cat 1_prep-terraform.sh
#!/bin/bash

APP_NAME="http://apim-demo-terraformsp"

subscription=$(az account show | jq -r .id)
sp=$(az ad sp create-for-rbac -n $APP_NAME --role="Contributor" --scopes="/subscriptions/$subscription")

export TF_VAR_CLIENT_ID=$(echo $sp | jq -r .appId)
export TF_VAR_CLIENT_SECRET=$(echo $sp | jq -r .password)
export TF_VAR_TENANT_ID=$(echo $sp | jq -r .tenant)
echo "The following terraform vars have been set"
for x in $(set | grep -i TF_VAR)
do
  echo "export "$x
done

echo "Please note that for the Keyvault piece...you need an Enterprise ID"
echo "TF_VAR_ENTERPRISE_ID= XXXXX"
echo "you find the Enterprise ObjectID in the Enterprise application app section of Azure AD, please note to select ALL APPS"
echo "NOTE!!!! you can only access this if you have sufficient rights on your tenant"

```
The above is the output I get

Paul

**Comment by chrisvugrinec** [comment]
hi Paul

this script is just simply put to set your environment variables..based on your comment 'When I run the script .\1_prep-terraform.sh' I am assuming your run this on a windows computer... in windows you need to set your environment variables like this: set VAR_NAME=.   ....  next to this, also note that I am using az-cli and not powershell (my preference is az-cli) ...let me know how you are travelling
